### ISSUE TITLE
Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

### ISSUE THREAD

**Issue by dimiro1** [leejarvis/atom-code-school-theme#2]
In index.less: Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

**Comment by aiomaster** [comment]
This issue should get closed, cause the shadow DOM is removed in atom:
http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html
